version: '3'
services:
  db:
    image: postgres:alpine
  app:
    build: .
    image: my_image:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
    - ./src:/app
    ports:
    - "3000:3000"
    links:
    - db:db
    depends_on:
    - db
